// File generated by the FlutterFire CLI. PLACEHOLDER — replace by running:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// from the project root once your Firebase project exists. That command
// overwrites this file with real keys for whichever platforms you select
// and registers the apps in your Firebase project automatically.
//
// Until then, Firebase.initializeApp() will throw with these placeholder
// values — that's intentional, so a half-configured project fails loudly
// instead of silently hitting a real (wrong) project.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web has not been configured. Run `flutterfire configure` to add it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS has not been configured. Run `flutterfire configure` to add it.',
        );
      default:
        throw UnsupportedError(
          '${defaultTargetPlatform.name} is not supported by this app yet.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBncQA2mwq1SgJEjH3Cg3Da2hYQrheTnOA',
    appId: '1:121909559512:android:b5421548a622a5bab717ad',
    messagingSenderId: '121909559512',
    projectId: 'geereel',
    storageBucket: 'geereel.firebasestorage.app',
  );
}
